#-------------------- ItemCase Configuration File --------------------#
# This file contains all of the ItemCase configuration settings that
# can be changed and altered.
#---------------------------------------------------------------------#

#Locale: en-us, de-de
Locale: en-us
    
#Update options
Updates:
    # Notify if an update is available. (Recommended)
    Check-For-Update: true
    # Use a custom API key for the ServerMods API. (Optional)
    API-Key: your_api_key
   
#Blocks that can be used for ItemCases.   
Blocks:
    - 44 #Slab
    - 126 #Wooded Slabs